framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%"
    default_locale: '%env(LOCALE)%'
    php_errors:
        log: true
    secret: '%env(APP_SECRET)%'
    session: false
