imports:
    - { resource: config.yml }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true

hautelook_alice:
    fixtures_path: fixtures
    root_dirs:
        - '%kernel.project_dir%'

monolog:
    handlers:
        console:
            channels:
                - '!console'
                - '!doctrine'
                - '!event'
            process_psr_3_messages: false
            type: console
        main:
            channels:
                - '!event'
            level: info
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            process_psr_3_messages: false
            type: stream

web_profiler:
    intercept_redirects: false
    toolbar: true
