_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error

_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler

_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

_main:
    resource: routing.yml
