security:
    providers:
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)/
            security: false
            stateless: true
        main:
            anonymous: ~
            stateless: true
