services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # ---

    app.bridge.api_platform.metadata.property.factory.property_name_collection:
        arguments:
            $decorated: '@app.bridge.api_platform.metadata.property.factory.property_name_collection.inner'
        decorates: api_platform.metadata.property.name_collection_factory
        class: AppBundle\Bridge\ApiPlatform\Metadata\Property\Factory\PropertyNameCollectionFactory

    app.bridge.doctrine.mapping.naming_strategy:
        class: AppBundle\Bridge\Doctrine\Mapping\NamingStrategy

    # ---

    AppBundle\Controller\ImageController:
        arguments:
            $filesystem: '@oneup_flysystem.tmp_filesystem'
        tags:
            - { name: controller.service_arguments }

    AppBundle\Controller\ResourceController:
        tags:
            - { name: controller.service_arguments }

    AppBundle\EventListener\MediaListener:
        arguments:
            $filesystem: '@oneup_flysystem.media_filesystem'
        tags:
            - { name: doctrine.event_listener , event: postLoad }
            - { name: doctrine.event_listener , event: postPersist }
            - { name: doctrine.event_listener , event: postRemove }

    AppBundle\Factory\ResourcePropertiesFactory:
        arguments:
            $filterLocator: '@api_platform.filter_locator'
            $itemsPerPage: '%api_platform.collection.pagination.items_per_page%'
