services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        exclude: ../src/{Bridge,Entity,Migrations,Tests}
        resource: ../src/*

    App\Controller\:
        resource: ../src/Controller
        tags:
            - { name: controller.service_arguments }

    App\Factory\ResourcePropertiesFactory:
        arguments:
            $filterLocator: '@api_platform.filter_locator'
            $itemsPerPage: '%api_platform.collection.pagination.items_per_page%'
