services:

    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        exclude: ../src/{Bridge,Entity,Migrations,Tests}
        resource: ../src/*

    App\Controller\:
        resource: ../src/Controller
        tags:
            - { name: controller.service_arguments }

    App\Controller\ImageController:
        arguments:
            $filesystem: '@oneup_flysystem.tmp_filesystem'

    App\EventListener\MediaListener:
        arguments:
            $filesystem: '@oneup_flysystem.media_filesystem'
        tags:
            - { name: doctrine.event_listener , event: postLoad }
            - { name: doctrine.event_listener , event: postPersist }
            - { name: doctrine.event_listener , event: postRemove }

    App\Factory\ResourcePropertiesFactory:
        arguments:
            $filterLocator: '@api_platform.filter_locator'
            $itemsPerPage: '%api_platform.collection.pagination.items_per_page%'
